# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-21 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlmapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmap',
            name='key',
            field=models.CharField(choices=[('terms-and-conditions', 'terms-and-conditions'), ('awards', 'awards')], max_length=64, unique=True, verbose_name='Key'),
        ),
    ]
