# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-03 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlmapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmap',
            name='key',
            field=models.CharField(choices=[(b'tigtag_url', b'tigtag_url'), (b'junior_url', b'junior_url'), (b'terms-and-conditions', b'terms-and-conditions'), (b'awards', b'awards'), (b'how-to-use-ttj', b'how-to-use-ttj'), (b'how-to-use-tt', b'how-to-use-tt')], max_length=64, unique=True, verbose_name='Key'),
        ),
    ]
